services:
  - type: web
    name: hyper-personalized-ai-ld-coach
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: GROQ_API_KEY
        sync: false
